Add Banner message to page header
opendifferentialprivacy/opendp-ux pull request #454
Opened 2021-12-14 17:05 UTC by ekraffmiller

2021-12-15 18:07 UTC, raprasad requested changes
please see review

2021-12-15 18:07 UTC, raprasad commented on client/src/components/Structure/Header.vue
> +      if (this.bannerMessages) {
The UI should be able to display multiple banner messages--the API will only return active banner messages

2021-12-15 18:49 UTC, ekraffmiller commented on client/src/components/Structure/Header.vue
> +      if (this.bannerMessages) {
I just pushed a change to display a list of messages

2021-12-15 18:53 UTC, ekraffmiller commented on client/src/components/Structure/Header.vue
> +      if (this.bannerMessages) {
I just realized I removed the condition for displaying the box - need to do one more change

2022-01-03 14:59 UTC, raprasad approved these changes, later dismissed

2022-01-03 14:59 UTC, raprasad commented on client/src/components/Structure/Header.vue
> +                      <div v-html="message.content"></div>
Add some kind of "spacer"/mark between messages. e.g. something like:

```html
                   <li v-for="(message, index) in bannerMessages">
                      <div v-html="message.content"></div>
                        <hr v-if="index != Object.keys(bannerMessages).length - 1" style="margin:10px 0; color:#cccccc;" />
                    </li>
```

2022-01-03 16:41 UTC, raprasad approved these changes
approved

2022-01-03 17:18 UTC, merged