464 multi tabs
opendifferentialprivacy/opendp-ux pull request #472
Opened 2022-01-13 12:34 UTC by ekraffmiller

use localStorage to share login state between tabs

2022-01-15 00:28 UTC, raprasad requested changes
In testing locally, I'm opening multiple tabs (2 to 3) and when logging out, I'm frequently running into the following error:
<img width="965" alt="DP_Creator" src="https://user-images.githubusercontent.com/1036060/149601184-0791a9b8-8d09-44b3-bfef-764f5c36d14b.png">

2022-01-15 00:40 UTC, raprasad commented
@ekraffmiller May be able to reproduce with a clean install and:
(note: only 1 user)
(1) tab 1: log in with dev_admin; click "MyProfile"; click "My Data"
(2) tab 2: login with dev_admin; click "MyProfile"; click "My Data"
(3) tab 1: click "Log out"

2022-01-18 12:31 UTC, ekraffmiller commented
@raprasad I was able to reproduce that error - it was happening because the current page is updated after logout, even though the user is redirected to the home page.  I added a condition to check the value of datasets before rendering the v-data-table.

2022-01-18 15:19 UTC, raprasad approved these changes

2022-01-18 15:19 UTC, merged